In [19]:
import random
import sympy
import numpy as np

# GD for single variable, analytic

In [ ]:
cur_x = random.randint(-1000,1000) # The algorithm starts at x=3
rate = 0.01 # Learning rate
precision = math.pow(10,-9) #This tells us when to stop the algorithm
previous_step_size = 1 #
max_iters = 10000 # maximum number of iterations
iters = 0 #iteration counter
df = lambda x: 2*(x+5) #Gradient of our function

In [ ]:
while previous_step_size > precision and iters < max_iters:
    prev_x = cur_x #Store current x value in prev_x
    cur_x = cur_x - rate * df(prev_x) #Grad descent
    previous_step_size = abs(cur_x - prev_x) #Change in x
    iters = iters+1 #iteration count
    print("Iteration",iters,"\nX value is",cur_x) #Print iterations
    
print("The local minimum occurs at ", cur_x)
print("Probably the true minimum is at ", round(cur_x, abs(int(math.log10(precision)))-3))

In [ ]:
print('We have found a local minimum at \n{} with a delta of \n{} running \n{} iterations'.format(cur_x, previous_step_size, iters))

# GD for multi variable, analytical

In [16]:
sympy.init_printing()
x_sym, y_sym, z_sym = sympy.symbols('x y z', real=True)
f = 4*x_sym*y_sym + x_sym*sympy.sin(z_sym) + x_sym**3 + z_sym**8*y_sym

In [80]:
cur_pos = np.matrix([random.randint(-10, 10),random.randint(-10, 10),random.randint(-10, 10)]).transpose()
rate = 0.1 # Learning rate
precision = 10**-9 #This tells us when to stop the algorithm
previous_step_size = np.matrix([1, 1, 1]) #
max_iters = 5 # maximum number of iterations
iters = 0 #iteration counter
df = [sympy.diff(f,x_sym), sympy.diff(f,y_sym), sympy.diff(f,z_sym)]

In [82]:
while np.linalg.norm(previous_step_size) > precision and iters < max_iters:
    prev_pos = cur_pos
    grad_x = df[0].subs([(x_sym, prev_pos[0]),(y_sym, prev_pos[1]), (z_sym, prev_pos[2])])
    grad_y = df[1].subs([(x_sym, prev_pos[0]), (z_sym, prev_pos[2])])
    grad_z = df[2].subs([(x_sym, prev_pos[0]),(y_sym, prev_pos[1]), (z_sym, prev_pos[2])])
    grad = np.matrix([grad_x, grad_y, grad_z]).transpose()
    cur_pos = np.multiply(cur_pos, grad) * rate
    previous_step_size = abs(prev_pos-cur_pos) #Change in x
    iters += 1 #iteration count
    print("Iteration",iters,"\nX value is",cur_pos) #Print iterations

Iteration 1 
X value is [[-3.20907025731743]
 [-234.000000000000]
 [-1843.28322936731]]


TypeError: loop of ufunc does not support argument 0 of type Float which has no callable sqrt method

In [83]:
n = np.matrix([1, 2, 3]).transpose()
print(n)
m = np.matrix([4, 5, 6])
print(m)
print(n * m)
print(np.multiply(n,m.transpose()))
print(n[0])

[[1]
 [2]
 [3]]
[[4 5 6]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4]
 [10]
 [18]]
[[1]]


NameError: name 'astype' is not defined

In [76]:
grad_x = df[0].item().expand()
grad_x.subs([(x_sym, 1), (y_sym, 2)])

In [79]:
cur_pos[0]

TypeError: 'builtin_function_or_method' object is not subscriptable